services:
  db:
    image: postgres:17.5
    container_name: postgres_clean
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/